---
- name: "Actualizar Clave de Usuario {{ user_name }}"
  hosts: all
  gather_facts: yes
  gather_timeout: 15
  ignore_unreachable: yes

  vars:
    enviarmail: "No"
    nueva_password:
    email_host: "172.22.88.6"
    email_from: "edduin.arias.Ext@claro.com.co"
    email_to: "{{ email_user | default(ansible_env.MAIL, true) | default('admin@claro.com.co', true) }}"
    email_subject: "Cambio de Clave en LineaBase"
    email_port: 25
    new_password_hash: "{{ nueva_password | password_hash('sha512', 'S4ltHpuX99') }}"

  tasks:
    - name: "Verificar si el usuario existe en el host remoto"
      ansible.builtin.command: "id {{ user_name }}"
      register: usuario_existe
      ignore_errors: yes
      changed_when: false

    - name: "Validar que nueva_password no esté vacía"
      ansible.builtin.fail:
        msg: "La variable nueva_password no puede estar vacía"
      when: nueva_password is not defined or nueva_password == ""

    # ================== HP-UX ==================
    - name: Cambiando Password usuarios en HP-UX
      ansible.builtin.raw: "/usr/sbin/usermod -p '{{ new_password_hash }}' {{ user_name }}"
      when:
        - ansible_facts['os_family'] == 'HP-UX'
        - usuario_existe.rc == 0        
      register: estado_cambio_hpux
      ignore_errors: yes
      failed_when: false

    # ================== Linux ==================
    - name: "Cambiar contraseña de usuario en sistemas Linux"
      ansible.builtin.user:
        name: "{{ user_name }}"
        password: "{{ nueva_password | password_hash('sha512') }}"
        update_password: always
      register: estado_cambio_linux
      when:
        - usuario_existe.rc == 0
        - ansible_facts['os_family'] in ['RedHat', 'Debian', 'Suse', 'AlmaLinux']
      ignore_errors: yes
      failed_when: false

    - name: "Desbloquear cuenta en Linux"
      ansible.builtin.command: "passwd -u {{ user_name }}"
      when:
        - usuario_existe.rc == 0
        - ansible_facts['os_family'] in ['RedHat', 'Debian', 'Suse', 'AlmaLinux']
      ignore_errors: yes
      failed_when: false

    - name: "Resetear intentos fallidos faillock"
      ansible.builtin.command: "faillock --user {{ user_name }} --reset"
      when: 
        - ansible_facts['os_family'] in ['RedHat', 'Debian', 'Suse', 'AlmaLinux']
      ignore_errors: yes
      failed_when: false

    - name: "Resetear intentos fallidos pam_tally"
      ansible.builtin.command: "pam_tally2 --user={{ user_name }} --reset"
      when: 
        - ansible_facts['os_family'] in ['RedHat', 'Debian', 'Suse', 'AlmaLinux']
      ignore_errors: yes
      failed_when: false

    # ================== AIX ==================
    - name: "[AIX] Verificar si pexpect está instalado"
      ansible.builtin.shell: |
        /opt/freeware/bin/python3.7 -m pip show pexpect >/dev/null 2>&1
      register: pexpect_check
      failed_when: false
      changed_when: false
      when: ansible_facts['os_family'] == 'AIX'
    
    - name: "[AIX] Instalar pexpect (si falta)"
      ansible.builtin.shell: |
        /opt/freeware/bin/python3.7 -m pip install pexpect --quiet
      when: ansible_facts['os_family'] == 'AIX' and pexpect_check.rc != 0
      ignore_errors: yes
      failed_when: false
    
    - name: "[AIX] Cambiar contraseña de usuario usando expect"
      ansible.builtin.expect:
        command: "passwd {{ user_name }}"
        responses:
          "(?i)new password": "{{ nueva_password }}"
          "(?i)re-enter": "{{ nueva_password }}"
          "(?i)enter the new password again": "{{ nueva_password }}"
          "(?i)enter new password": "{{ nueva_password }}"
        timeout: 60
      register: estado_cambio_aix
      when:
        - ansible_facts['os_family'] == 'AIX'
        - usuario_existe.rc == 0
      ignore_errors: yes
      failed_when: false

    - name: "[AIX] Quitar flag de cambio forzado de contraseña"
      ansible.builtin.command: "pwdadm -c {{ user_name }}"
      when:
        - ansible_facts['os_family'] == 'AIX'
        - usuario_existe.rc == 0
      ignore_errors: yes
      failed_when: false

    # ================== Solaris ==================
    - name: "[Solaris] Generar hash SHA-256 compatible (en nodo remoto)"
      ansible.builtin.shell: |
        python3 -c 'import crypt; print(crypt.crypt("{{ nueva_password }}", crypt.mksalt(crypt.METHOD_SHA256)))'
      register: pass_hash
      when:
        - usuario_existe.rc == 0
        - ansible_facts['os_family'] == 'Solaris'
      changed_when: false
      failed_when: false
    
    - name: "[Solaris] Actualizar campo de contraseña en /etc/shadow"
      ansible.builtin.replace:
        path: /etc/shadow
        regexp: '^({{ user_name }}):[^:]*:(.*)$'
        replace: '\1:{{ pass_hash.stdout }}:\2'
        backup: yes
      register: estado_cambio_solaris
      when:
        - ansible_facts['os_family'] == 'Solaris'
        - usuario_existe.rc == 0
      ignore_errors: yes
      failed_when: false

    # ================== Registro de resultados ==================
    - name: "Registrar resultados del cambio de contraseña"
      ansible.builtin.set_fact:
        cambio_resultado:
          host: "{{ inventory_hostname }}"
          usuario: "{{ user_name }}"
          estado: >-
            {% if usuario_existe.rc is defined and usuario_existe.rc != 0 %}
              Falló
            {% elif (estado_cambio_linux is defined and estado_cambio_linux.changed | default(false)) %}
              Éxito
            {% elif (estado_cambio_hpux is defined and estado_cambio_hpux.rc | default(1) == 0) %}
              Éxito
            {% elif (estado_cambio_aix is defined and estado_cambio_aix.rc | default(1) == 0) %}
              Éxito
            {% elif (estado_cambio_solaris is defined and estado_cambio_solaris.changed | default(false)) %}
              Éxito
            {% else %}
              Falló
            {% endif %}
      when: user_name is defined
      ignore_errors: yes
      failed_when: false

    - name: Enviar correo del Reporte
      become: false
      mail:
        host: "{{ email_host }}"
        port: "{{ email_port }}"
        subject: "{{ email_subject }}"
        subtype: html
        body: "{{ lookup('template', 'email_template.j2') }}"   
        from: "{{ email_from }}"
        to: "{{ email_to }}"
      delegate_to: localhost
      run_once: yes
      when: enviarmail == 'Si'
      ignore_errors: yes
